[project]
name = "surya-environment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "marker-pdf==1.8.0",
    "matplotlib>=3.10.8",
    "memory-profiler>=0.61.0",
]
