[project]
name = "mineru-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "memory-profiler>=0.61.0",
    "mineru[core]>=2.6.8",
]
